services:
  mariadb:
    image: mariadb
    ports: 
      - 3306:3306
    environment:
      MARIADB_USER: madoff
      MARIADB_PASSWORD: madoff
      MARIADB_DATABASE: madoff
      MARIADB_ROOT_PASSWORD: toor
  php:
    image: php:fpm
    volumes:
      - .:/var/www/html
  nginx:
    ports: 
      - 80:80
    image: nginx
    volumes:
      - ./.docker/default.nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public
